In [83]:
!pip install  streamlit

/Users/tejsai/.zshenv:export:1: not valid in this context: hello.java
Requirement already satisfied: streamlit in /Applications/anaconda3/lib/python3.12/site-packages (1.37.1)
Requirement already satisfied: altair<6,>=4.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in /Applications/anaconda3/lib/python3.12/site-packages (from streamlit) (6.4.1)
Requirement already satisfied: jinja2 in /Applications/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /Applications/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in /Applications/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /Applications/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Applications/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Applications/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Applications/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Applications/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Applications/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /Applications/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Applications/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Applications/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Applications/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in /Applications/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)

In [84]:
##load data
data=pd.read_csv('Heart_Disease_Dataset.csv')
data.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,Yes,14.96,Yes,Yes,No,7,6,Yes,Female,25-29,White,Yes,Yes,Fair,17.1,Yes,Yes,Yes
1,Yes,36.93,Yes,Yes,No,3,10,No,Female,30-34,Hispanic,"No, borderline diabetes",Yes,Poor,2.7,Yes,No,No
2,No,18.70,Yes,No,Yes,26,15,No,Male,70-74,Hispanic,No,No,Poor,15.6,Yes,Yes,Yes
3,Yes,31.43,Yes,Yes,Yes,24,20,No,Female,40-44,American Indian/Alaskan Native,"No, borderline diabetes",No,Fair,1.4,No,No,Yes
4,Yes,75.64,No,No,Yes,2,29,No,Male,35-39,White,No,Yes,Excellent,8.8,Yes,Yes,Yes

In [85]:
data.tail()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
100196,No,48.02,No,No,Yes,13,17,No,Female,45-49,White,"No, borderline diabetes",No,Fair,6.4,Yes,No,No
100197,Yes,82.88,No,No,No,29,23,No,Male,75-79,Other,"No, borderline diabetes",Yes,Very good,18.9,Yes,Yes,No
100198,No,39.46,No,Yes,Yes,23,6,Yes,Male,80 or older,Hispanic,Yes,No,Excellent,18.5,Yes,No,Yes
100199,No,46.25,Yes,Yes,Yes,9,14,No,Male,25-29,American Indian/Alaskan Native,No,No,Very good,22.7,Yes,Yes,No
100200,No,39.26,Yes,No,No,10,5,Yes,Female,25-29,Other,"No, borderline diabetes",Yes,Fair,4.1,No,No,Yes

In [86]:
#information about columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100201 entries, 0 to 100200
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      100201 non-null  object
 1   BMI               100201 non-null  float64
 2   Smoking           100201 non-null  object
 3   AlcoholDrinking   100201 non-null  object
 4   Stroke            100201 non-null  object
 5   PhysicalHealth    100201 non-null  int64
 6   MentalHealth      100201 non-null  int64
 7   DiffWalking       100201 non-null  object
 8   Sex               100201 non-null  object
 9   AgeCategory       100201 non-null  object
 10  Race              100201 non-null  object
 11  Diabetic          100201 non-null  object
 12  PhysicalActivity  100201 non-null  object
 13  GenHealth         100201 non-null  object
 14  SleepTime         100201 non-null  float64
 15  Asthma            100201 non-null  object
 16  KidneyDisease     100201 non-null  object
 17  SkinCancer        100201 non-null  object
dtypes: float64(2), int64(2), object(14)
memory usage: 13.8+ MB

In [87]:
data.shape

(100201, 18)

In [88]:
#statstical analysis
data.describe()

                 BMI  PhysicalHealth   MentalHealth      SleepTime
count  100201.000000   100201.000000  100201.000000  100201.000000
mean       53.373302       14.503937      14.498239      12.490389
std        23.878712        8.640423       8.658639       6.632122
min        12.020000        0.000000       0.000000       1.000000
25%        32.760000        7.000000       7.000000       6.700000
50%        53.380000       14.000000      15.000000      12.500000
75%        73.950000       22.000000      22.000000      18.200000
max        94.850000       29.000000      29.000000      24.000000

In [89]:
#checking null values
data.isnull().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [90]:
#duplicates
data.duplicated().sum()

0

In [91]:
data.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
100196    False
100197    False
100198    False
100199    False
100200    False
Length: 100201, dtype: bool

In [92]:
data.columns

Index(['HeartDisease', 'BMI', 'Smoking', 'AlcoholDrinking', 'Stroke',
       'PhysicalHealth', 'MentalHealth', 'DiffWalking', 'Sex', 'AgeCategory',
       'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth', 'SleepTime',
       'Asthma', 'KidneyDisease', 'SkinCancer'],
      dtype='object')

In [93]:
for column in data.columns:
  print(f'{column}:{data[column].unique()}')

HeartDisease:['Yes' 'No']
BMI:[14.96 36.93 18.7  ... 15.41 91.36 36.29]
Smoking:['Yes' 'No']
AlcoholDrinking:['Yes' 'No']
Stroke:['No' 'Yes']
PhysicalHealth:[ 7  3 26 24  2 12  5  6 19 11  8 16 20  4 15  1  9 14 27  0 17 28 29 23
 18 10 25 21 22 13]
MentalHealth:[ 6 10 15 20 29 27 13  7  2 25 11 26 12 28 14 22 16  5  1  0 24  9 21 23
  8  4  3 17 18 19]
DiffWalking:['Yes' 'No']
Sex:['Female' 'Male']
AgeCategory:['25-29' '30-34' '70-74' '40-44' '35-39' '50-54' '75-79' '60-64' '18-24'
 '55-59' '65-69' '45-49' '80 or older']
Race:['White' 'Hispanic' 'American Indian/Alaskan Native' 'Black' 'Asian'
 'Other']
Diabetic:['Yes' 'No, borderline diabetes' 'No' 'Yes (during pregnancy)']
PhysicalActivity:['Yes' 'No']
GenHealth:['Fair' 'Poor' 'Excellent' 'Good' 'Very good']
SleepTime:[17.1  2.7 15.6  1.4  8.8  4.8 12.  22.4 16.3 20.9  3.5 19.1 15.9 10.4
 18.9 19.  17.4  7.1  1.  20.6 21.6 11.4 10.5  5.6  4.5 22.7 20.8  7.
 21.2 18.2 15.2 13.2  1.1 18.6  6.6 20.3 10.8 19.2 16.2 23.6  4.9 23.5
  1.3 18.8 22.9  4.7 16.1 16.5  7.8 13.1  6.   5.1  9.4  6.9  3.1 19.9
 17.5  7.2  5.4  3.6 10.3 14.4  3.3 15.7 17.9  4.4  1.5 14.8 17.  18.5
  7.3 12.6 11.   8.3 18.7 19.7  6.1 10.  12.9  9.  15.1 20.4 14.2 19.8
  5.7 22.8  3.8  4.1  9.1 23.3 20.   5.   6.4 12.2  3.4 12.5 10.6  8.5
 17.7  2.3  7.6 22.3  1.8 16.7 18.   5.8 14.1  1.7  5.3 21.7  3.9 23.
  2.2 22.  21.3  4.3 14.5 19.6 23.4  7.4 11.5  3.7 20.1  2.5 23.9  9.9
 21.1  6.2  2.4 14.6  6.3  2.1 10.9 21.4  7.9 23.7 17.3 15.4  7.5  8.
  8.4 15.8 12.7 21.5 19.3 18.4  8.7  4.6 18.3  3.2  1.2  5.5  7.7 15.3
  3.  21.8 13.3 11.9 19.4  6.8 11.3  9.3 11.7 11.6 13.6 11.2 16.   9.5
  4.   4.2  5.2  2.   2.9 20.5 13.8 15.  22.6  9.8 18.1 19.5 22.1  6.7
 10.2 17.2 20.2 23.1  8.2 12.1  5.9  1.6 14.9  8.6 20.7 16.9  6.5 11.1
 16.8  8.9 16.6 13.5 14.   9.7  9.2 12.8 22.5  1.9 10.1 14.7 11.8 16.4
 21.9 13.7 23.8 10.7 13.9 15.5 17.6  2.8 22.2 12.3  2.6  9.6  8.1 21.
 12.4 14.3 17.8 23.2 13.4 13.  24. ]
Asthma:['Yes' 'No']
KidneyDisease:['Yes' 'No']
SkinCancer:['Yes' 'No']

In [94]:
for column in data.columns:
  print(data[column].value_counts())

HeartDisease
Yes    50134
No     50067
Name: count, dtype: int64
BMI
56.38    26
91.47    26
27.95    26
88.49    26
66.39    25
         ..
23.75     3
29.15     3
65.14     3
34.33     2
91.36     2
Name: count, Length: 8284, dtype: int64
Smoking
Yes    50445
No     49756
Name: count, dtype: int64
AlcoholDrinking
Yes    50435
No     49766
Name: count, dtype: int64
Stroke
Yes    50265
No     49936
Name: count, dtype: int64
PhysicalHealth
8     3430
20    3401
9     3395
16    3392
19    3386
13    3385
12    3377
26    3369
29    3363
15    3355
23    3354
22    3347
28    3345
14    3343
2     3341
1     3337
10    3334
11    3332
6     3329
0     3328
17    3327
7     3323
24    3316
5     3305
18    3301
3     3287
21    3285
27    3277
25    3270
4     3267
Name: count, dtype: int64
MentalHealth
27    3442
16    3442
13    3419
5     3403
26    3397
21    3394
22    3390
7     3382
2     3377
8     3376
1     3374
18    3367
14    3362
28    3361
6     3360
3     3357
20    3342
9     3336
23    3333
17    3317
0     3299
19    3284
25    3280
10    3279
29    3274
11    3269
4     3257
15    3252
12    3247
24    3229
Name: count, dtype: int64
DiffWalking
Yes    50153
No     50048
Name: count, dtype: int64
Sex
Female    50243
Male      49958
Name: count, dtype: int64
AgeCategory
80 or older    7851
18-24          7850
55-59          7801
40-44          7789
25-29          7710
75-79          7697
70-74          7694
45-49          7680
60-64          7673
35-39          7641
50-54          7634
65-69          7591
30-34          7590
Name: count, dtype: int64
Race
Hispanic                          16898
Asian                             16834
White                             16708
American Indian/Alaskan Native    16650
Black                             16582
Other                             16529
Name: count, dtype: int64
Diabetic
Yes (during pregnancy)     25171
No, borderline diabetes    25077
Yes                        25001
No                         24952
Name: count, dtype: int64
PhysicalActivity
No     50397
Yes    49804
Name: count, dtype: int64
GenHealth
Good         20342
Poor         20180
Fair         19986
Excellent    19939
Very good    19754
Name: count, dtype: int64
SleepTime
18.9    499
16.4    492
2.3     487
21.3    483
10.3    480
       ...
23.2    395
1.3     394
18.6    388
24.0    234
1.0     196
Name: count, Length: 231, dtype: int64
Asthma
Yes    50118
No     50083
Name: count, dtype: int64
KidneyDisease
Yes    50264
No     49937
Name: count, dtype: int64
SkinCancer
No     50426
Yes    49775
Name: count, dtype: int64

In [95]:
#one hot encoding
data=pd.get_dummies(data,columns=['Diabetic'],drop_first=True)
data.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,"Diabetic_No, borderline diabetes",Diabetic_Yes,Diabetic_Yes (during pregnancy)
0,Yes,14.96,Yes,Yes,No,7,6,Yes,Female,25-29,White,Yes,Fair,17.1,Yes,Yes,Yes,False,True,False
1,Yes,36.93,Yes,Yes,No,3,10,No,Female,30-34,Hispanic,Yes,Poor,2.7,Yes,No,No,True,False,False
2,No,18.70,Yes,No,Yes,26,15,No,Male,70-74,Hispanic,No,Poor,15.6,Yes,Yes,Yes,False,False,False
3,Yes,31.43,Yes,Yes,Yes,24,20,No,Female,40-44,American Indian/Alaskan Native,No,Fair,1.4,No,No,Yes,True,False,False
4,Yes,75.64,No,No,Yes,2,29,No,Male,35-39,White,Yes,Excellent,8.8,Yes,Yes,Yes,False,False,False

In [96]:
#convert binary categorical variables into numerical columns
binary_cols=['Sex','Smoking','AlcoholDrinking','PhysicalActivity','Asthma','KidneyDisease','SkinCancer']
for col in binary_cols:
  data[col]=data[col].map({'Yes':1,'No':0})

In [97]:
binary_cols

['Sex',
 'Smoking',
 'AlcoholDrinking',
 'PhysicalActivity',
 'Asthma',
 'KidneyDisease',
 'SkinCancer']