In [1]:
!pip install mlxtend

/Users/tejsai/.zshenv:export:1: not valid in this context: hello.java
Requirement already satisfied: mlxtend in /Applications/anaconda3/lib/python3.12/site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /Applications/anaconda3/lib/python3.12/site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in /Applications/anaconda3/lib/python3.12/site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in /Applications/anaconda3/lib/python3.12/site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /Applications/anaconda3/lib/python3.12/site-packages (from mlxtend) (1.5.1)
Requirement already satisfied: matplotlib>=3.0.0 in /Applications/anaconda3/lib/python3.12/site-packages (from mlxtend) (3.9.2)
Requirement already satisfied: joblib>=0.13.2 in /Applications/anaconda3/lib/python3.12/site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /Applications/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /Applications/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Applications/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Applications/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Applications/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (24.1)
Requirement already satisfied: pillow>=8 in /Applications/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Applications/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /Applications/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Applications/anaconda3/lib/python3.12/site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Applications/anaconda3/lib/python3.12/site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Applications/anaconda3/lib/python3.12/site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in /Applications/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns

In [3]:
titanic=pd.read_csv('Titanic 2.csv')
titanic.head()

  Class Gender    Age Survived
0   3rd   Male  Child       No
1   3rd   Male  Child       No
2   3rd   Male  Child       No
3   3rd   Male  Child       No
4   3rd   Male  Child       No

In [4]:
titanic['Class'].unique()

array(['3rd', '1st', '2nd', 'Crew'], dtype=object)

In [5]:
titanic['Class'].value_counts()

Class
Crew    885
3rd     706
1st     325
2nd     285
Name: count, dtype: int64

pre processing

In [6]:
titanic['Age'].unique()

array(['Child', 'Adult'], dtype=object)

In [7]:
titanic['Age'].value_counts()

Age
Adult    2092
Child     109
Name: count, dtype: int64

In [9]:
titanic['Gender'].unique()
titanic['Gender'].value_counts()

Gender
Male      1731
Female     470
Name: count, dtype: int64

In [10]:
df=pd.get_dummies(titanic,dtype=int)
df.head()

,Class_1st,Class_2nd,Class_3rd,Class_Crew,Gender_Female,Gender_Male,Age_Adult,Age_Child,Survived_No,Survived_Yes
0,0,0,1,0,0,1,0,1,1,0
1,0,0,1,0,0,1,0,1,1,0
2,0,0,1,0,0,1,0,1,1,0
3,0,0,1,0,0,1,0,1,1,0
4,0,0,1,0,0,1,0,1,1,0

In [16]:
#Apriori algorithm

In [18]:
titanic.shape[0]

2201

In [50]:
frequent_itemsets=apriori(df,min_support=0.1,use_colnames=True)
frequent_itemsets

     support                                           itemsets
0   0.147660                                        (Class_1st)
1   0.129487                                        (Class_2nd)
2   0.320763                                        (Class_3rd)
3   0.402090                                       (Class_Crew)
4   0.213539                                    (Gender_Female)
5   0.786461                                      (Gender_Male)
6   0.950477                                        (Age_Adult)
7   0.676965                                      (Survived_No)
8   0.323035                                     (Survived_Yes)
9   0.144934                             (Age_Adult, Class_1st)
10  0.118582                             (Age_Adult, Class_2nd)
11  0.231713                           (Class_3rd, Gender_Male)
12  0.284871                             (Class_3rd, Age_Adult)
13  0.239891                           (Survived_No, Class_3rd)
14  0.391640                          (Class_Crew, Gender_Male)
15  0.402090                            (Class_Crew, Age_Adult)
16  0.305770                          (Survived_No, Class_Crew)
17  0.193094                         (Age_Adult, Gender_Female)
18  0.156293                      (Survived_Yes, Gender_Female)
19  0.757383                           (Gender_Male, Age_Adult)
20  0.619718                         (Survived_No, Gender_Male)
21  0.166742                        (Survived_Yes, Gender_Male)
22  0.653339                           (Survived_No, Age_Adult)
23  0.297138                          (Survived_Yes, Age_Adult)
24  0.209905                (Class_3rd, Gender_Male, Age_Adult)
25  0.191731              (Survived_No, Class_3rd, Gender_Male)
26  0.216265                (Survived_No, Class_3rd, Age_Adult)
27  0.391640               (Class_Crew, Age_Adult, Gender_Male)
28  0.304407             (Survived_No, Class_Crew, Gender_Male)
29  0.305770               (Survived_No, Class_Crew, Age_Adult)
30  0.143571           (Age_Adult, Survived_Yes, Gender_Female)
31  0.603816              (Survived_No, Gender_Male, Age_Adult)
32  0.153567             (Survived_Yes, Age_Adult, Gender_Male)
33  0.175829   (Survived_No, Class_3rd, Gender_Male, Age_Adult)
34  0.304407  (Survived_No, Class_Crew, Age_Adult, Gender_Male)

In [22]:
rules=association_rules(frequent_itemsets,metric='lift',min_threshold=1,num_itemsets=len(frequent_itemsets))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Gender_Male),(Age_Adult),0.786461,0.950477,0.757383,0.963027,1.013204,1.0,0.009870,1.339441,0.061028,0.773191,0.253420,0.879936
1,(Age_Adult),(Gender_Male),0.950477,0.786461,0.757383,0.796845,1.013204,1.0,0.009870,1.051116,0.263149,0.773191,0.048630,0.879936
2,(Survived_No),(Gender_Male),0.676965,0.786461,0.619718,0.915436,1.163995,1.0,0.087312,2.525187,0.436144,0.734518,0.603990,0.851710
3,(Gender_Male),(Survived_No),0.786461,0.676965,0.619718,0.787984,1.163995,1.0,0.087312,1.523634,0.659783,0.734518,0.343674,0.851710
4,(Survived_No),(Age_Adult),0.676965,0.950477,0.653339,0.965101,1.015386,1.0,0.009900,1.419023,0.046906,0.670709,0.295290,0.826241
5,(Age_Adult),(Survived_No),0.950477,0.676965,0.653339,0.687380,1.015386,1.0,0.009900,1.033317,0.305968,0.670709,0.032243,0.826241
6,"(Survived_No, Gender_Male)",(Age_Adult),0.619718,0.950477,0.603816,0.974340,1.025106,1.0,0.014788,1.929980,0.064404,0.624824,0.481860,0.804809
7,"(Survived_No, Age_Adult)",(Gender_Male),0.653339,0.786461,0.603816,0.924200,1.175139,1.0,0.089991,2.817152,0.429921,0.722283,0.645032,0.845982
8,"(Gender_Male, Age_Adult)",(Survived_No),0.757383,0.676965,0.603816,0.797241,1.177669,1.0,0.091095,1.593193,0.621823,0.727024,0.372330,0.844593
9,(Survived_No),"(Gender_Male, Age_Adult)",0.676965,0.757383,0.603816,0.891946,1.177669,1.0,0.091095,2.245337,0.467023,0.727024,0.554633,0.844593
10,(Gender_Male),"(Survived_No, Age_Adult)",0.786461,0.653339,0.603816,0.767764,1.175139,1.0,0.089991,1.492710,0.697935,0.722283,0.330078,0.845982
11,(Age_Adult),"(Survived_No, Gender_Male)",0.950477,0.619718,0.603816,0.635277,1.025106,1.0,0.014788,1.042660,0.494550,0.624824,0.040914,0.804809

In [26]:
rules.sort_values('lift',ascending=False)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
8,"(Gender_Male, Age_Adult)",(Survived_No),0.757383,0.676965,0.603816,0.797241,1.177669,1.0,0.091095,1.593193,0.621823,0.727024,0.372330,0.844593
9,(Survived_No),"(Gender_Male, Age_Adult)",0.676965,0.757383,0.603816,0.891946,1.177669,1.0,0.091095,2.245337,0.467023,0.727024,0.554633,0.844593
7,"(Survived_No, Age_Adult)",(Gender_Male),0.653339,0.786461,0.603816,0.924200,1.175139,1.0,0.089991,2.817152,0.429921,0.722283,0.645032,0.845982
10,(Gender_Male),"(Survived_No, Age_Adult)",0.786461,0.653339,0.603816,0.767764,1.175139,1.0,0.089991,1.492710,0.697935,0.722283,0.330078,0.845982
2,(Survived_No),(Gender_Male),0.676965,0.786461,0.619718,0.915436,1.163995,1.0,0.087312,2.525187,0.436144,0.734518,0.603990,0.851710
3,(Gender_Male),(Survived_No),0.786461,0.676965,0.619718,0.787984,1.163995,1.0,0.087312,1.523634,0.659783,0.734518,0.343674,0.851710
6,"(Survived_No, Gender_Male)",(Age_Adult),0.619718,0.950477,0.603816,0.974340,1.025106,1.0,0.014788,1.929980,0.064404,0.624824,0.481860,0.804809
11,(Age_Adult),"(Survived_No, Gender_Male)",0.950477,0.619718,0.603816,0.635277,1.025106,1.0,0.014788,1.042660,0.494550,0.624824,0.040914,0.804809
4,(Survived_No),(Age_Adult),0.676965,0.950477,0.653339,0.965101,1.015386,1.0,0.009900,1.419023,0.046906,0.670709,0.295290,0.826241
5,(Age_Adult),(Survived_No),0.950477,0.676965,0.653339,0.687380,1.015386,1.0,0.009900,1.033317,0.305968,0.670709,0.032243,0.826241
0,(Gender_Male),(Age_Adult),0.786461,0.950477,0.757383,0.963027,1.013204,1.0,0.009870,1.339441,0.061028,0.773191,0.253420,0.879936
1,(Age_Adult),(Gender_Male),0.950477,0.786461,0.757383,0.796845,1.013204,1.0,0.009870,1.051116,0.263149,0.773191,0.048630,0.879936