In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
sns.get_dataset_names()#sample datasaets provided by pandas lib

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
df=sns.load_dataset('flights')  #accesing dataset
df
#pandas only generate 1d objs
#using dataframe obj 2d objs are generated

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [6]:
df1=sns.load_dataset('diamonds')#accesing dataset
df1

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [8]:
df.shape#gives

(144, 3)

In [13]:
df.columns#gives no.of cols

Index(['year', 'month', 'passengers'], dtype='object')

In [11]:
type(df)#datatype

pandas.core.frame.DataFrame

In [15]:
df.columns[0]#accesing

'year'

In [17]:
k=[1,2,3,4,5,6]
k

[1, 2, 3, 4, 5, 6]

In [19]:
pd.Series(k)#use 'uppercase for s'

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [20]:
j=[11,22,33,44,56,56,'india']#the  final dt type is string,if we mentioned float values it datatype changes to float
pd.Series(j)

0       11
1       22
2       33
3       44
4       56
5       56
6    india
dtype: object

In [ ]:
l=[12.3,12,45,56,67,'india']

0     12.3
1       12
2       45
3       56
4       67
5    india
dtype: object